# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('desc', models.CharField(max_length=200)),
                ('lastDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RssObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('desc', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('splash', models.URLField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rssReader.Channel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=set([('title', 'link')]),
        ),
        migrations.AlterUniqueTogether(
            name='rssobject',
            unique_together=set([('title', 'link', 'channel', 'pubDate')]),
        ),
    ]
