# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='feedURL',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='rssobject',
            name='splash',
            field=models.ImageField(blank=True, upload_to='splash_images'),
        ),
    ]
