# Generated by Django 2.1 on 2018-08-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0002_auto_20180802_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssobject',
            name='splash',
            field=models.URLField(blank=True),
        ),
    ]
